### ISSUE TITLE
Provider Methods, question

### ISSUE THREAD

**Issue by AmauryEsparza** [antoniolg/DaggerExample#2]
I'm little new on Dagger...
In the LoginModule you have this two provider methods

LoginModule...
@Provides @Singleton public LoginView provideView() { 
        return view;
    } 
@Provides @Singleton 
    public LoginPresenter providePresenter(LoginView loginView, LoginInteractor loginInteractor) {
        return new LoginPresenterImpl(loginView, loginInteractor);
  }

Where did you pass the LoginView and LoginInteractor parameters? and Why two provider methods if you only have one receiver parameter in LoginActivity?

LoginActivity...
@Inject LoginPresenter presenter;

Thanks!

**Comment by antoniolg** [comment]
LoginView is used by the LoginPresenter. You probably could get rid of that one and use it directly on providePresenter if you are not using it anywhere else. LoginPresenter is injected directly into LoginActivitiy, and will be provided by dagger thanks to this provider.

The LoginInteractor is defined in InteractorsModule.
